In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    # "day": [1, 2, 3, 4, 5, 6],

    "temperature": [20, 22, np.nan, np.nan, np.nan, 0]

})

print(df)

   temperature
0         20.0
1         22.0
2          NaN
3          NaN
4          NaN
5          0.0

In [13]:
df['dropna_temp'] = df['temperature'].dropna()
df['bfill_temp'] = df['temperature'].bfill()
df['ffill_temp'] = df['temperature'].ffill()
df['interpolate_temp'] = df['temperature'].interpolate()

df

   temperature  dropna_temp  bfill_temp  ffill_temp  interpolate_temp
0         20.0         20.0        20.0        20.0              20.0
1         22.0         22.0        22.0        22.0              22.0
2          NaN          NaN         0.0        22.0              16.5
3          NaN          NaN         0.0        22.0              11.0
4          NaN          NaN         0.0        22.0               5.5
5          0.0          0.0         0.0         0.0               0.0

In [11]:
df

   day  temperature  dropna_temp  bfill_temp  ffill_temp  interpolate_temp
0    1         20.0         20.0        20.0        20.0              20.0
1    2         22.0         22.0        22.0        22.0              22.0
2    3          NaN          NaN         0.0        22.0              16.5
3    4          NaN          NaN         0.0        22.0              11.0
4    5          NaN          NaN         0.0        22.0               5.5
5    6          0.0          0.0         0.0         0.0               0.0

In [5]:
df['temperature'].bfill()

0    20.0
1    22.0
2    30.0
3    30.0
4    30.0
5    32.0
Name: temperature, dtype: float64

In [25]:
import pandas as pd

df1 = pd.DataFrame({
    "student_id": [1, 2, 3, 4, None],
    "score": [4, 6, 8, 5, 7]
})

df1

   student_id  score
0         1.0      4
1         2.0      6
2         3.0      8
3         4.0      5
4         NaN      7

In [18]:
# Calculate mean
total_score = df1['score'].sum()
total_points = df1['score'].count()
mean_score = total_score / total_points
mean_score

np.float64(6.0)

In [23]:
df1['score'].std()

np.float64(1.5811388300841898)

In [26]:
df1.describe().T

            count  mean       std  min   25%  50%   75%  max
student_id    4.0   2.5  1.290994  1.0  1.75  2.5  3.25  4.0
score         5.0   6.0  1.581139  4.0  5.00  6.0  7.00  8.0

In [28]:
df1.fillna(0, inplace=True)

In [29]:
df1['student_id'].count()

np.int64(5)